### ISSUE TITLE
TASK .. run update and reboot using.. takes forever with multiple hosts (one after the other)

### ISSUE THREAD

**Issue by crpb** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update#12]
I had that issues often enough now but today as i currently am updating 18 hosts to the 24.7.2 i'm annoyed again.
Did some digging and the only thing i could find and which would make sense is [throttle](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_strategies.html) when i'm not mistaken.

i found a few [occurences](https://github.com/search?q=org%3ARosa-Luxemburgstiftung-Berlin+throttle&type=code) of that option but not directly in either -facts or -update which are the roles i have in the playbook (and -plugpack as it seems /o\). And i don't see how that should trigger here?

Does anybody else has the same wait times or might that just be because i did something wrong?

I don't wanna stop it now and probably have just to try it again when the next update comes but that couldn't take too long 😆 

```
- name: opnsense
  hosts:
    - opnsense
    - opnsensetest
  strategy: free
  vars:
    ansible_become: false
  roles:
    - role: ansible-opnsense-facts
      tags:
        - opnsense
        - facts
    - role: ansible-opnsense-plugpack
      tags:
        - opnsense
        - plugpack
    - role: ansible-opnsense-update
      tags:
        - opnsense
        - update
          #    - role: ansible-opnsense-checkmk
          #      tags:
          #        - opnsense
          #        - checkmk
```

```
ansible-playbook -e opn_update_desired_version=24.7.2 -D update.yaml -l   631.38s user 105.27s system 18% cpu 1:07:12.23 total
```
