### ISSUE TITLE
How to use ansible-opnsense-update & facts

### ISSUE THREAD

**Issue by tweak19** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update#20]
Hi,
I currently trying to use your roles, but I am not sure how is the correct way to add this to my existing ansible setup.
If i try to add it with ansible-galaxy collection install git+ xxx I get an error that no name is specificated.

Could you please be so fine and made an short explanation how to use?
Would be great to make automatic upgrades on my opnsense ;-)

Thx
Kind regards

**Comment by zerwes** [comment]
Hello @tweak19 and thank you for your interest in our roles.

We tried to offer some sample on how we use the roles in https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-playbook

A improvement of the documentation is on the way as a PR in Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-playbook#1 - maybe you finde some interesting informations there

In general you can write your playbook like this cloning the repos as roles:
```yaml
- name: opnsense
  hosts: opnsense
  vars:
    ansible_become: no
  roles:
    # ...
    - role: opnsense-facts # git clone https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-facts.git roles/opnsense-facts
      tags:
        - opnsense
        - facts
        - always
    - role: opnsense # git clone https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense.git roles/opensense
      tags:
        - opnsense
    - role: ansible-opnsense-update # git clone https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update.git roles/
      tags:
        - opnsense
        - update
    # ...
```

I will have a look at the option to install the roles via ansible-galaxy and update the docs accordingly (I'll keep this issue open for this) ...

Hope this helps.
If there are other questions, just let me know...
